### ISSUE TITLE
cudatext-cn@1.194.0.0: hash check failed

### ISSUE THREAD

**Issue by willtse** [ViCrack/scoop-bucket#2]
Installing 'cudatext-cn' (1.194.0.0) [64bit] from ViCrack_scoop-bucket bucket
Loading cudatext-windows-amd64-1.194.0.0.zip from cache
Checking hash of cudatext-windows-amd64-1.194.0.0.zip ... ok.
translation.zh_CN.zip (7.0 KB) [==========================================================] 100%
Checking hash of translation.zh_CN.zip ... ERROR Hash check failed!
App:         ViCrack_scoop-bucket/cudatext-cn
URL:         https://downloads.sourceforge.net/project/cudatext/addons/translations/translation.zh_CN.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    39bc8ee31e53b990032938d898e91b63590c0ef831b9cd3b863ddd7d7ccdb0ba
Actual:      b2a78ad04ae5b6e762be51399c53e89ab88efe8021e98b774e66c7227152630a

![image](https://github.com/ViCrack/scoop-bucket/assets/328654/dd46502c-0cfd-4eb2-affa-3ef2b081a8e9)

**Comment by ViCrack** [comment]
已经修复

暂时也可以用`scoop install cudatext-cn -s`来安装

**Comment by ViCrack** [comment]
没认真看，先将就用吧，晚点我再补🌝
