### ISSUE TITLE
pot.json 安装错误

### ISSUE THREAD

**Issue by huruka** [ViCrack/scoop-bucket#3]
我估计应该是因为 pot 做过大改动
提供的 nsis.zip 解压出来里面其实是个 nsis 安装包，不是可执行程序；并且配置文件 config.toml 好像也没在用了，换成了用户配置文件夹中的 .json 配置……等等

**Comment by ViCrack** [comment]
是改动多了

现在我已经换成了用setup.exe

[https://github.com/ViCrack/scoop-bucket/commit/ec9ae94dd332db7e4e3cf931381dba45166fad8c](https://github.com/ViCrack/scoop-bucket/commit/ec9ae94dd332db7e4e3cf931381dba45166fad8c)


还有问题的话再说
