### ISSUE TITLE
apifox: Update to version 2.x.x

### ISSUE THREAD

**Issue by willtse** [ViCrack/scoop-bucket#5]
最近好像每天 apifox 的版本号都会变来变去，请问是怎么回事呢...

![图片](https://github.com/ViCrack/scoop-bucket/assets/328654/9bf13f5a-469c-4122-bcdc-e57d1313f314)

**Comment by ViCrack** [comment]
修复了，这是因为之前的校验方式firefox版本号总是动态变化
