### ISSUE TITLE
[Request] please update rubick

### ISSUE THREAD

**Issue by scil** [ViCrack/scoop-bucket#6]
latest is v4 https://github.com/rubickCenter/rubick/releases

it's v3 here 
https://github.com/ViCrack/scoop-bucket/blob/master/bucket/rubick.json

**Comment by ViCrack** [comment]
OK

[https://github.com/ViCrack/scoop-bucket/blob/master/bucket/rubick.json](https://github.com/ViCrack/scoop-bucket/blob/master/bucket/rubick.json)
